theme: minima
title: Seattle Seahawks
author: Mohammed Al-Azadi
email: malazadi127@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Welcome to the Seattle Seahawks fanpage!
  
  

# social links
twitter_username: _twinmohammed # DO NOT include the @ character, or else the build will fail!
github_username:  malazadi # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
